services:
  otel-collector:
    container_name: "shopping-collector-demo"
    image: "otel/opentelemetry-collector-contrib:0.109.0"
    command: [ "--config=/etc/otel-collector-config.yaml" ]
    volumes:
      - "./opentelemetry-collector-contrib/config.yaml:/etc/otel-collector-config.yaml"
    ports:
      - "1888:1888"   # pprof extension
      - "8888:8888"   # Prometheus metrics exposed by the collector
      - "8889:8889"   # Prometheus exporter metrics
      - "4317:4317"   # OTLP gRPC receiver
      - "4318:4318"   # OTLP HTTP receiver
      - "13133:13133" # health_check extension
      - "55679:55679" # zpages extension
    depends_on:
      - jaeger
      - zipkin
      - prometheus
      - loki
    networks:
      - otel-network

  jaeger:
    container_name: "shopping-jaeger-demo"
    image: "jaegertracing/all-in-one:1.60.0"
    ports:
      - "16686:16686"   # Jaeger UI
      - "14268"
      - "14250"         # Jaeger HTTP collector port (internal)
      - "4317"          # Jaeger OTLP/gRPC collector port (internal)
    networks:
      - otel-network

  zipkin:
    container_name: "shopping-zipkin-demo"
    image: "openzipkin/zipkin:3.4.1"
    environment:
      - JAVA_OPTS=-Xms1024m -Xmx1024m -XX:+ExitOnOutOfMemoryError
    ports:
      - "9411:9411"    # Zipkin UI and collector
    networks:
      - otel-network

  prometheus:
    container_name: "shopping-prometheus-demo"
    image: "prom/prometheus:v2.54.1"
    volumes:
      - "./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"    # Prometheus UI
    networks:
      - otel-network

  loki:
    container_name: "shopping-loki-demo"
    image: "grafana/loki:3.1.1"
    ports:
      - "3100:3100"    # Loki API
    command: [ "-config.file=/etc/loki/local-config.yaml" ]
    volumes:
      - "./grafana/loki/loki-config.yaml:/etc/loki/local-config.yaml"
    networks:
      - otel-network

  grafana:
    container_name: "shopping-grafana-demo"
    image: "grafana/grafana-oss:11.2.0"
    ports:
      - "3000:3000"    # Grafana UI
    depends_on:
      - otel-collector
      - jaeger
      - zipkin
      - prometheus
      - loki
    networks:
      - otel-network

networks:
  otel-network:
    name: "shopping-network-demo"
    driver: bridge
