spring:
  application:
    name: 'Catalogue'

  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: 'demo'
    password: 'Shopping Demo 2024'

  datasource:
    hikari:
      jdbc-url: 'jdbc:h2:mem:demo-catalogue;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=MYSQL'
      username: 'demo'
      password: 'Catalogue'

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none

  kafka:
    bootstrap-servers: 'localhost:9092'
    producer:
      group-id: 'demo'
      key-serializer: 'org.apache.kafka.common.serialization.StringSerializer'
      value-serializer: 'org.springframework.kafka.support.serializer.JsonSerializer'

server:
  port: 8081
