spring:
  application:
    name: 'Shopping'

  datasource:
    hikari:
      jdbc-url: 'jdbc:h2:mem:demo;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=MYSQL'
      username: 'demo'
      password: 'Shopping Demo 2024'

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
